/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTIMPORTDECLARATION = 1;
  public int JJTCLASSDECLARATION = 2;
  public int JJTVARDECLARATION = 3;
  public int JJTMETHODDECLARATION = 4;
  public int JJTCLASSMETHOD = 5;
  public int JJTSTATICFUNCTION = 6;
  public int JJTINSTRUCTIONS = 7;
  public int JJTTYPE = 8;
  public int JJTSTATEMENT = 9;
  public int JJTEXPRESSION = 10;
  public int JJTEXPRESSIONRIGHT = 11;


  public String[] jjtNodeName = {
    "Program",
    "ImportDeclaration",
    "ClassDeclaration",
    "VarDeclaration",
    "MethodDeclaration",
    "ClassMethod",
    "StaticFunction",
    "Instructions",
    "Type",
    "Statement",
    "Expression",
    "ExpressionRight",
  };
}
/* JavaCC - OriginalChecksum=46b9cf74496bd437d65e99ce5deb54b4 (do not edit this line) */
