/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTEXPRESSIONRIGHT = 2;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "ExpressionRight",
  };
}
/* JavaCC - OriginalChecksum=bea20a3ffd8c870a97758971e0ca5232 (do not edit this line) */
